# Generated by Django 4.1 on 2022-10-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
