# Generated by Django 4.1 on 2022-10-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(),
        ),
    ]
